### PR TITLE
changed class to style class #58

### LINKED ISSUE #40: Do not use an attribute called class.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/user/admin/users.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/users.jsp)
+ **LineNum**: [35](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/users.jsp#L35)
+ **Code**:    `<div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/user/admin/users.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/users.jsp)
+ **LineNum**: [35](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/users.jsp#L35)

### LINKED ISSUE #41: Do not use an attribute called class.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/user/admin/users.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/users.jsp)
+ **LineNum**: [67](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/users.jsp#L67)
+ **Code**:    `<div><span class="small text-gray-500">December 12, 2019</span>`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/user/admin/users.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/users.jsp)
+ **LineNum**: [70](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/users.jsp#L70)

### LINKED ISSUE #42: Do not use an attribute called class.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/user/admin/users.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/users.jsp)
+ **LineNum**: [72](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/users.jsp#L72)
+ **Code**:    `<div class="bg-success icon-circle"><i class="fas fa-donate text-white"></i></div>`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/user/admin/users.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/users.jsp)
+ **LineNum**: [75](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/users.jsp#L75)

### LINKED ISSUE #43: Do not use an attribute called class.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/error/404.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/error/404.jsp)
+ **LineNum**: [25](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/error/404.jsp#L25)
+ **Code**:    `<li class="nav-item"><a class="nav-link" href="../user/dashboard.html"><i class="fa fa-dashboard"></i><span>Dashboard</span></a></li>`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/error/404.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/error/404.jsp)
+ **LineNum**: [25](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/error/404.jsp#L25)

### LINKED ISSUE #44: Avoid having style information in JSP files.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/error/404.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/error/404.jsp)
+ **LineNum**: [27](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/error/404.jsp#L27)
+ **Code**:    `<li class="nav-item"><a class="nav-link" href="../user/submissions.html"><i class="fa fa-table"></i><span>Submission</span></a></li>`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/error/404.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/error/404.jsp)
+ **LineNum**: [27](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/error/404.jsp#L27)

### LINKED ISSUE #45: Do not use an attribute called class.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/error/404.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/error/404.jsp)
+ **LineNum**: [37](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/error/404.jsp#L37)
+ **Code**:    `<div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/error/404.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/error/404.jsp)
+ **LineNum**: [37](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/error/404.jsp#L37)

### LINKED ISSUE #46: Do not use an attribute called class.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/error/404.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/error/404.jsp)
+ **LineNum**: [49](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/error/404.jsp#L49)
+ **Code**:    `<div class="bg-primary icon-circle"><i class="fas fa-file-alt text-white"></i></div>`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/error/404.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/error/404.jsp)
+ **LineNum**: [49](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/error/404.jsp#L49)

### LINKED ISSUE #47: Do not use an attribute called class.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/user/admin/user.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/user.jsp)
+ **LineNum**: [61](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/user.jsp#L61)
+ **Code**:    `<div class="input-group-append"><button class="btn btn-primary py-0" type="button" style="background: var(--purple);"><i class="fas fa-search"></i></button></div>`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/user/admin/user.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/user.jsp)
+ **LineNum**: [64](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/user.jsp#L64)

### LINKED ISSUE #48: Do not use an attribute called class.
#### Occurred on:
+ **Commit**:  e65d8b7021e5ee73f580c2fed2f38bde660fae59
+ **File**:    [src/main/webapp/user/admin/user.jsp](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/user.jsp)
+ **LineNum**: [65](https://github.com/elroykanye/cms-main/blob/e65d8b7021e5ee73f580c2fed2f38bde660fae59/src/main/webapp/user/admin/user.jsp#L65)
+ **Code**:    `<li class="nav-item dropdown no-arrow mx-1">`

    
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/user/admin/user.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/user.jsp)
+ **LineNum**: [68](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/user.jsp#L68)

### LINKED ISSUE #49: Do not use an attribute called class.
#### Currently on:
+ **Commit**:  3df79ae10341f89b872f2c22688e7015bc953081
+ **File**:    [src/main/webapp/user/admin/users.jsp](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/users.jsp)
+ **LineNum**: [40](https://github.com/elroykanye/cms-main/blob/3df79ae10341f89b872f2c22688e7015bc953081/src/main/webapp/user/admin/users.jsp#L40)

### PR DESCRIPTION
**Pull request by Jardon237**

### CODE REVIEW

**Review by elroykanye — CHANGES_REQUESTED** [review]
You were to address one commit per issue, then put but issue number.
Sorry I made a mistake. Put but the issue number, not line number. So that I'll know which issues you've fixed🙏🏾

**Comment by elroykanye** [comment]
You don't need to undo anything. Just edit the commit message on GitHub. If you can't do it, lemme know so I show you

**Comment by Jardon237** [comment]
I noticed the error when I had pushed it already. Just 2 commits have that
error. The rest are fine

**Comment by elroykanye** [comment]
Okay so which issues have you resolved?

**Review by elroykanye — APPROVED** [review]

**Pull request merged**
